run_name = "mnist_eval_example"
relu_layer_dim = 784
input_dim = 784
output_dim = 10
temperature = 50.0
leaky_slope = 0.01
num_relu_layers = 20
test_data_path = "mnist_test.csv"
load_weights_path = "mnist.bin"
