run_name = "mnist_eval_example"

[model_config]
relu_layer_dim = 1024
input_dim = 784
output_dim = 10
num_relu_layers = 10
temperature = 100.0

[testing_config]
test_data_path = "/Users/benchen/workspace/ice-nine/data/mnist_test.csv"

[save_config]
load_weights_path = "/Users/benchen/workspace/ice-nine/weights/mnist.bin"
