run_name = "mnist_train_example"

[model_config]
relu_layer_dim = 1024
input_dim = 784
output_dim = 10
num_relu_layers = 10
temperature = 100.0

[training_config]
train_data_path = "/Users/benchen/workspace/ice-nine/data/mnist_train.csv"
steps_to_train = 10000
microbatch_size = 20
learning_rate = 0.01
max_gradient = 10000.0

[testing_config]
test_data_path = "/Users/benchen/workspace/ice-nine/data/mnist_test.csv"
num_test_examples = 200
steps_per_test = 100

[save_config]
steps_per_save = 1000
save_weights_path = "/Users/benchen/workspace/ice-nine/weights/mnist.bin"
# load_weights_path = "/Users/benchen/workspace/ice-nine/weights/mnist.bin"
